name: GitHub Action 

on: 
  push:
    branches:    
      - main
      - dev
  pull_request:
    branches:    
      - main
      - dev

jobs:
  deploy:
    name: GitHub Pipeline
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Selecting Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode_15.4.app
        
      - name: Running Xcode version Is?
        run: /usr/bin/xcodebuild -version
   
      - name: Build Cleanup
        run: |
          xcodebuild clean -project HelloWorld.xcodeproj -scheme HelloWorld | xcpretty
          
      - name: Build Test
        run: |
          xcodebuild test -project HelloWorld.xcodeproj -scheme HelloWorld -destination 'platform=iOS   Simulator,name=iPhone 15,OS=18.1' | xcpretty -s
          
      - name: Build Archive
        uses: yukiarrr/ios-build-action@v1.5.0  
        with:
          project-path: HelloWorld.xcodeproj
          # workspace-path: GitHubAction.xcworkspace # optional
          scheme: HelloWorld
          configuration: Release
          export-method: app-store
          p12-key-base64: ${{ secrets.P12_KEY_BASE64 }}
          p12-cer-base64: ${{ secrets.P12_CER_BASE64 }}
          mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
          team-id: ${{ secrets.TEAM_ID }}
    
      - name: Saving IPA File
        uses: actions/upload-artifact@v3   
        with:
          name: ipa
          path: ./**.ipa
          
      # - name: Upload App
      #   if: success()
      #   env:
      #     APPLEID_USERNAME: ${{ secrets.APPLEID_USERNAME }}
      #     APPLEID_PASSWORD: ${{ secrets.APPLEID_PASSWORD }}
      #   run: |
      #     xcrun altool --upload-app -t ios -f ./**.ipa -u "$APPLEID_USERNAME" -p "$APPLEID_PASSWORD" --verbose
